[workspace]
resolver = "2"
members = [
    "crates/mous-proto",
    "crates/mous-core",
    "crates/mousd",
    "crates/mou",
    "crates/mous-bench",
]

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
postcard = { version = "1", features = ["alloc"] }
rusqlite = { version = "0.32", features = ["bundled"] }
time = { version = "0.3", features = ["formatting", "parsing", "macros"] }
clap = { version = "4", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
libc = "0.2"

mous-proto = { path = "crates/mous-proto" }
mous-core = { path = "crates/mous-core" }

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
